### PR TITLE
Expand rebuild explanation in changelog menu

### PR DESCRIPTION
**Pull request by tooomm**
See https://github.com/mtgjson/mtgjson-website/issues/241

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I don't care for the wording on this change. cc : @omfgitsmark

**Comment by staghouse** [comment]
I feel like if we are going to point out specific fields being updated then we should be general and say something to the effect that releases update fields containing timely data. How to word that? idk.

**Comment by ZeldaZach** [comment]
Pretty much. Every field gets brought up to date, so there's no reason to specify which

**Comment by staghouse** [comment]
Disregard: Testing webhook

**Comment by omfgitsmark** [comment]
Maybe an "e.g." would be appropriate?

"Below you can find all the changes made on each MTGJSON build release. Versions marked as rebuilds are fully backwards compatible with the release and contain updates for fields that need more frequent updating (e.g. prices and EDH Rank), as well as data improvements."

**Comment by omfgitsmark** [comment]
A few final tweaks, I think this sounds good:
> "Below you will find all the changes made on each MTGJSON build release. Versions marked as rebuilds are fully backwards compatible with the release and contain updates for fields that require more frequent updating (e.g. prices and EDH Rank), as well as data improvements."

**Pull request merged**
