### PR TITLE
issue/406 | add: changelog for 4.6.3

### PR DESCRIPTION
**Pull request by jroed**
Changelog might still need to be extended with other changes that occurred since last update if any.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I'm gonna handle the changelog notes myself, but I appreciate the initiative! I'll have them up by tonight :)

**Comment by jroed** [comment]
Great, I'm looking forward to it.

**Comment by ZeldaZach** [comment]
Deployed!

**Comment by jroed** [comment]
That was quick! Is there a Ikoria Promos set?

**Comment by ZeldaZach** [comment]
No. Promos are now bundled into the main set as they have different set numbers. In the past, they had the same set #, which caused problems.

**Comment by jroed** [comment]
Do you want to write `Ikoria` or `Ikoria: Lair of Behemoths`? We might come back to this Plane in the future.

**Comment by ZeldaZach** [comment]
It's `Ikoria: Lair of Behemoths (IKO)` guess I rushed haha. If you'd like to PR a fix to that, as well as how promos are bundled, would be appreciated

**Pull request closed without merging**
